"""empty message

Revision ID: 45903ee93639
Revises: 
Create Date: 2018-06-19 12:05:40.596684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45903ee93639'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dinner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('date', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dinner'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dinner')
    # ### end Alembic commands ###
